# Generated by Django 5.1.2 on 2024-11-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Addmission_start_date', models.DateField(blank=True, null=True)),
                ('Addmission_end_name', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='collegemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_code', models.IntegerField(blank=True, null=True)),
                ('coures', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Contact_number', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=25, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('University', models.CharField(blank=True, choices=[('CENTER', 'center'), ('CALICUT', 'calicut'), ('COCHIN', 'cochin'), ('NATIONAL', 'national')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('notification_content', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
