# Generated by Django 5.1.2 on 2024-11-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='college_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
