# Generated by Django 5.1.2 on 2024-11-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_collegemodel_college_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='college_img/')),
                ('titel', models.CharField(blank=True, max_length=30, null=True)),
                ('Discription', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
