# Generated by Django 5.1.2 on 2024-11-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_homeview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmission_details',
            old_name='Addmission_end_name',
            new_name='Addmission_end_date',
        ),
        migrations.AddField(
            model_name='addmission_details',
            name='Eligibility',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addmission_details',
            name='Subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
