# Generated by Django 5.1.2 on 2024-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_rename_addmission_end_name_addmission_details_addmission_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmission_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sslc_certificate', models.FileField(blank=True, null=True, upload_to='Files')),
                ('Plustwo_certificate', models.FileField(blank=True, null=True, upload_to='Files')),
                ('ID_card', models.FileField(blank=True, null=True, upload_to='Files')),
                ('TC', models.FileField(blank=True, null=True, upload_to='Files')),
                ('CC', models.FileField(blank=True, null=True, upload_to='Files')),
            ],
        ),
    ]
