# Generated by Django 5.1.2 on 2024-11-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_addmission_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission_documents',
            name='CC',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='addmission_documents',
            name='ID_card',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='addmission_documents',
            name='Plustwo_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='addmission_documents',
            name='Sslc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.AlterField(
            model_name='addmission_documents',
            name='TC',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
    ]
