# Generated by Django 5.1.2 on 2024-11-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='programm_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(blank=True, max_length=25, null=True)),
                ('Venue', models.CharField(blank=True, max_length=25, null=True)),
                ('Start_date', models.DateTimeField(blank=True, null=True)),
                ('End_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
