# Generated by Django 5.1.2 on 2024-11-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_programm_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeview',
            old_name='Discription',
            new_name='Location',
        ),
    ]
