# Generated by Django 5.1.2 on 2024-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_rename_discription_homeview_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='homeview',
            name='Discripition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
