# Generated by Django 5.1.2 on 2024-12-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_college_vacancy_homeview_discripition'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeview',
            name='university_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.university'),
        ),
    ]
