# Generated by Django 5.1.2 on 2024-12-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_homeview_university_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='college_vacancy',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='University',
        ),
    ]
