# Generated by Django 5.1.2 on 2024-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_delete_college_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='college_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
