# Generated by Django 5.1.2 on 2024-12-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_collegemodel_college_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegemodel',
            name='coures',
        ),
    ]
