# Generated by Django 5.1.2 on 2024-12-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_alter_homeview_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeview',
            name='university_name',
        ),
    ]
