# Generated by Django 5.1.2 on 2025-01-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_item_ratingandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnotification',
            name='college',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='exam_notifications', to='college.collegemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='notification_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examnotification',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
