# Generated by Django 5.1.2 on 2025-01-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_examnotification_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegemodel',
            name='status',
        ),
    ]
