# Generated by Django 5.1.2 on 2025-01-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_remove_collegemodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingandreview',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ratingandreview',
            name='user',
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme', models.CharField(blank=True, max_length=30, null=True)),
                ('Totel_Seat', models.IntegerField(blank=True, null=True)),
                ('Availbale_Seat', models.IntegerField(blank=True, null=True)),
                ('Dead_line', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='RatingAndReview',
        ),
    ]
