# Generated by Django 5.1.2 on 2025-01-14 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_delete_homeview_rename_user_vacancy_connect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(blank=True, max_length=3000, null=True)),
                ('connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.collegemodel')),
            ],
        ),
    ]
