# Generated by Django 5.1.2 on 2025-01-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
