# Generated by Django 5.1.2 on 2025-01-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_about_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
