# Generated by Django 5.1.2 on 2025-01-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_alter_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='titel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
