# Generated by Django 5.1.2 on 2025-01-21 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0027_about_titel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='college_images/')),
                ('team_member_title', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member_description', models.TextField(blank=True, null=True)),
                ('team_member_image', models.ImageField(blank=True, null=True, upload_to='team_member_images/')),
                ('connect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.collegemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
