# Generated by Django 5.1.2 on 2025-01-21 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0028_college_delete_about'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='about',
        ),
    ]
