# Generated by Django 5.1.2 on 2025-01-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_rename_college_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='team_member_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='team_member_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='team_member_title',
        ),
    ]
