# Generated by Django 5.1.2 on 2025-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0030_remove_about_team_member_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='teamimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='teamimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='teammember1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='teammember2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
