# Generated by Django 5.1.2 on 2025-01-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_about_teamimg1_about_teamimg2_about_teammember1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='camimg1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='camimg2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='camimg3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
