# Generated by Django 5.1.2 on 2025-01-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0032_about_camimg1_about_camimg2_about_camimg3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='teamimg1',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='teamimg2',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
