# Generated by Django 5.1.2 on 2025-01-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0033_alter_about_teamimg1_alter_about_teamimg2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='teammember1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='teammember2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
