# Generated by Django 5.1.2 on 2025-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0034_alter_about_description_alter_about_teammember1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='teamimg3',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
