# Generated by Django 5.1.2 on 2025-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('STUDENT', 'student'), ('COLLEGE', 'college')], max_length=20, null=True),
        ),
    ]
