# Generated by Django 5.1.2 on 2024-11-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('Ph_num', models.IntegerField(blank=True, null=True)),
                ('Addar_num', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
