# Generated by Django 5.1.2 on 2024-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='University',
            field=models.CharField(blank=True, choices=[('CENTER', 'center'), ('CALICUT', 'calicut'), ('COCHIN', 'cochin'), ('NATIONAL', 'national')], max_length=20, null=True),
        ),
    ]
