# Generated by Django 5.1.2 on 2024-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(blank=True, max_length=30, null=True)),
                ('titel', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripition', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], max_length=20, null=True)),
            ],
        ),
    ]
