# Generated by Django 5.1.2 on 2025-01-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
