# Generated by Django 5.1.2 on 2025-01-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_delete_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
