# Generated by Django 5.1.2 on 2025-01-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_delete_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request',
        ),
    ]
