# Generated by Django 5.1.2 on 2025-01-22 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_complaint_complaintreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date_submitted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='student',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('under_review', 'Under Review'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComplaintReply',
        ),
    ]
