# Generated by Django 5.1.2 on 2025-01-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_rename_date_submitted_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
        ),
    ]
