# Generated by Django 5.1.2 on 2025-01-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_complaint_is_active_complaint_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lock',
        ),
    ]
