# Generated by Django 5.1.1 on 2024-12-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0002_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='riply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Reply', models.CharField(blank=True, max_length=40, null=True)),
                ('Riplay_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
