# Generated by Django 5.1.1 on 2024-12-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='riply',
        ),
    ]
